server:
  port: 8088

# 下面的地址时连接到docker容器中cassandra
#spring:
#  data:
#    cassandra:
#      cluster-name: Test Cluster
#      keyspace-name: test_spoints
#      contact-points: 192.168.199.116
#      port: 50070
